name: Publish

on:
  push:
    branches:
      - master

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Execute SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BLOG_URL }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: "cd lukehansford.me; git pull; yarn release"
